# Power management
CONFIG_PM=y
CONFIG_PM_DEVICE=y
CONFIG_POWEROFF=y

# GPIO
CONFIG_GPIO=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_BUFFER_SIZE=8192

# Set PM module (pm_em32) log level to DBG to see pm_state_set() traces
CONFIG_PM_LOG_LEVEL_DBG=y

# Set GPIO driver log level to DBG to see em32_pwr_wkup_pin_cfg_pupd() traces
CONFIG_GPIO_LOG_LEVEL_DBG=y

# SOC log level DBG
CONFIG_SOC_LOG_LEVEL_DBG=y

# EM32 wakeup pins support
CONFIG_EM32_WKUP_PINS=y
