# Copyright (c) 2026 ELAN Microelectronics Corp.
# SPDX-License-Identifier: Apache-2.0

# GPIO driver
CONFIG_GPIO=y
CONFIG_GPIO_EM32=y

# Pins are described in the device tree (DTS method)
CONFIG_PINCTRL=y
CONFIG_PINCTRL_EM32=y

# SPI2 loopback test
CONFIG_SPI=y

# Console output
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
